# GitHub Actions workflow: Cloudflare Worker を自動でデプロイする例
# 必要な Secrets:
# - CF_API_TOKEN  (Cloudflare API Token with Workers permissions)
# - CF_ACCOUNT_ID (Cloudflare account id)
name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Wrangler
        run: npm install -g wrangler@2

      - name: Publish worker
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          # wrangler は wrangler.toml を参照して publish します
          wrangler publish
